steps:
  # Uses the docker build step to build an image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "{_GCP_REGION}-docker.pkg.dev/encyclo-flower/us/${_IMG_NAME}",
        ".",
      ]

# my-image is pushed to Container Registry
images:
  - "{_GCP_REGION}-docker.pkg.dev/encyclo-flower/us/${_IMG_NAME}"

options:
  logging: CLOUD_LOGGING_ONLY
