# This workflow should control anything to do with detection service
# Including tests, building the docker image and pushing it
# It should run on both development and production scenarios
# Production workflow (tagging the image as "latest") should run only on tagged version push

name: Detection service

on:
  workflow_dispatch:
  release: # * https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [released]
  push:
    branches: [main]
    tags:
      - "v*.*.*"
    paths:
      # NOTE: Path filters are ignored for tag pushes
      - "src/services/image_recognition/**"
      - "tests/image_recognition/**"
  pull_request:
    branches: [main]
    paths:
      - "src/services/image_recognition/**"
      - "tests/image_recognition/**"
      - ".github/workflows/detection-svc.yml"

env:
  DOCKER_IMAGE_NAME: ohad24/${{ github.event.repository.name }}-detect-svc

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0-dev libportaudio2
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov requests
          pip install -r src/services/image_recognition/requirements.txt
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "Download PlantDetect.tflite model"
        run: "gcloud storage cp gs://ef-prod-private/PlantDetect.tflite src/services/image_recognition/"
      - name: Lint with flake8
        run: |
          # TODO: configure flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest --cov=tests/image_recognition --cov-report=xml tests/image_recognition/test_detection.py
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: "actions/checkout@v3"
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests google-auth
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "Download PlantDetect.tflite model"
        run: "gcloud storage cp gs://ef-prod-private/PlantDetect.tflite src/services/image_recognition/"
      - name: "Build tmp image"
        working-directory: "src/services/image_recognition/"
        run: "gcloud builds submit --gcs-log-dir=gs://ef-test-gh-actions/build-logs --suppress-logs --tag us-central1-docker.pkg.dev/encyclo-flower/us/ef-test-detect-plant-tmp"
      - name: "Run tmp container"
        run: "gcloud run deploy ef-test-detect-plant-tmp --image us-central1-docker.pkg.dev/encyclo-flower/us/ef-test-detect-plant-tmp --region us-central1"
      - name: "Test tmp container"
        run: |
          pytest tests/image_recognition/test_cloud_run.py \
            --url=$(gcloud run services describe ef-test-detect-plant-tmp --region us-central1 --format=json | \
                    jq .status.url --raw-output)
      - name: "Delete tmp container"
        run: "gcloud run services delete ef-test-detect-plant-tmp --region us-central1 --quiet"

  # * dev subdomain / pre-production
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/heads/main' && github.event_name != 'release'}}
    steps:
      - uses: "actions/checkout@v3"
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "Download PlantDetect.tflite model"
        run: "gcloud storage cp gs://ef-prod-private/PlantDetect.tflite src/services/image_recognition/"
      - name: "Build dev image"
        working-directory: "src/services/image_recognition/"
        run: "gcloud builds submit --gcs-log-dir=gs://ef-test-gh-actions/build-logs --suppress-logs --tag us-central1-docker.pkg.dev/encyclo-flower/us/ef-dev-detect-plant"
      - name: "Run tmp container"
        run: "gcloud run deploy ef-dev-detect-plant --image us-central1-docker.pkg.dev/encyclo-flower/us/ef-dev-detect-plant --region --region us-central1"

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/heads/main' && github.event_name == 'release'}}
    steps:
      - uses: "actions/checkout@v3"
