name: Docker Image CI (GCP-vision)

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/services/gcp_vision/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'src/services/gcp_vision/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build src/services/gcp_vision --file src/services/gcp_vision/Dockerfile --tag encyclo-flower/vision:test-$(date +%s)
